apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ai-planet-demo-rollout
  namespace: ai-planet-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-planet-demo-rollout
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 1}
      - setWeight: 60
      - pause: {duration: 1}
      - setWeight: 100
      - pause: {duration: 1}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: ai-planet-demo-rollout
    spec:
      containers:
      - name: ai-planet-demo-rollout
        image: lulad7/ai-planet-demo:1.2
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
