apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-planet-demo-hpa
  namespace: ai-planet-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Rollout
    name: myapp
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 256
