apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-planet-demo-hpa
  namespace: ai-planet-demo
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ai-planet-demo-rollout
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 256
