apiVersion: v1
kind: Service
metadata:
  name: ai-planet-service
  namespace: ai-planet-demo
spec:
  selector:
    app: ai-planet-demo
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 3005
